Handle Java 1.6 vs 1.7 automatically Better readme, update for SDK 17

diff --git a/bin/make-project b/bin/make-project
--- a/bin/make-project
+++ b/bin/make-project
@@ -30,12 +30,12 @@ NAME=$2
 ACTIVITY=$3
 PKG=$4
 
-android create project --target ${TARGET} --name ${NAME} --activity ${ACTIVITY} --path ${NAME} --package ${PKG}
+android create project --target ${TARGET} --name ${NAME} --activity ${ACTIVITY} --path ${NAME} --package ${PKG} > /dev/null || (echo "Failed to create an android project! File a bug at github.com/abarbu/android-kawa" && exit 1)
 rm -f ${NAME}/src/${PKG_PATH}/${ACTIVITY}.jar
 touch ${NAME}/src/${PKG_PATH}/${ACTIVITY}.scm
 ln -s `pwd`/kawa/kawa-1.*.jar ${NAME}/libs/kawa.jar
 
-cat > ${NAME}/build.xml.patch <<EOF
+(cd ${NAME}; (patch -p0 <<\EOF
 --- build.xml.orig	2010-10-11 15:48:59.092681778 -0700
 +++ build.xml	2010-11-04 22:26:34.565673740 -0700
 @@ -64,4 +64,27 @@
@@ -67,8 +67,8 @@ cat > ${NAME}/build.xml.patch <<EOF
 +
  </project>
 EOF
-
-(cd ${NAME}; patch < build.xml.patch)
+) > /dev/null \
+  || (echo "Failed to patch the build file! File a bug at github.com/abarbu/android-kawa" && exit 1))
 echo "adb shell kill \$(adb shell ps|grep -i ${PKG}|awk  '{ print $2 }') > /dev/null" > ${NAME}/make-and-send
 echo "ant debug && adb install -r bin/${NAME}-debug.apk && adb shell am start -a android.intent.action.MAIN ${PKG}/.${ACTIVITY}" >> ${NAME}/make-and-send
 chmod +x ${NAME}/make-and-send
diff --git a/bin/setup-kawa b/bin/setup-kawa
--- a/bin/setup-kawa
+++ b/bin/setup-kawa
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 set -e
+set -o pipefail
 
 EXPECTED_ARGS=2
 E_BADARGS=65
@@ -10,14 +11,8 @@ KAWA_VERSION=1.13
 if [ $# -lt $EXPECTED_ARGS ]; then
     echo "Usage: `basename $0` android-home android-platform"
     echo "	Setup a Kawa install in the current directory for a particular Android version."
-    echo "	for example: bin/setup-kawa /opt/android-sdk-update-manager android-14"
+    echo "	for example: bin/setup-kawa /opt/android-sdk-update-manager android-17"
     exit $E_BADARGS
-fi
-
-if [[ -z $(javac -version 2>&1 | grep 1.6) ]]; then
-    echo "Your javac is not version 1.6.*"
-    echo "   dex can't process files from any other version, you'll need to downgrade"
-    exit
 fi
 
 echo "Fetching Kawa ${KAWA_VERSION}"
@@ -30,8 +25,40 @@ fi
 tar xvf kawa-1.13.tar.gz
 mv kawa-${KAWA_VERSION} kawa
 cd kawa
+echo "Patching kawa"
+patch -p0 <<\EOF
+--- Makefile.am.orig	2013-07-17 09:36:47.448268287 -0400
++++ Makefile.am	2012-11-22 02:11:40.000000000 -0500
+@@ -258,7 +258,7 @@
+ COMMENT_OUT = s|^\([[:space:]]*\)\([^/[:space:]]\)|\1// \2|
+ 
+ gnu/kawa/util/PreProcess.class: $(srcdir)/gnu/kawa/util/PreProcess.java
+-	$(JAVAC) -d . $(srcdir)/gnu/kawa/util/PreProcess.java
++	$(JAVAC) -d . $(JAVACFLAGS) $(srcdir)/gnu/kawa/util/PreProcess.java
+ 
+ # JDK 1.1
+ select-java1: $(srcdir)/patch-source-list gnu/kawa/util/PreProcess.class
+EOF
+patch -p0 <<\EOF
+--- Makefile.in.orig	2013-07-17 09:36:49.229268472 -0400
++++ Makefile.in	2012-12-09 02:29:46.000000000 -0500
+@@ -959,7 +959,7 @@
+ 	  | sed -e 's|./||' | sort > $@
+ 
+ gnu/kawa/util/PreProcess.class: $(srcdir)/gnu/kawa/util/PreProcess.java
+-	$(JAVAC) -d . $(srcdir)/gnu/kawa/util/PreProcess.java
++	$(JAVAC) -d . $(JAVACFLAGS) $(srcdir)/gnu/kawa/util/PreProcess.java
+ 
+ # JDK 1.1
+ select-java1: $(srcdir)/patch-source-list gnu/kawa/util/PreProcess.class
+EOF
 echo "Building kawa"
-./configure --with-android=$1/platforms/$2/android.jar --disable-xquery --disable-jemacs
+JAVACFLAGS="-source 1.6 -target 1.6" ./configure --with-android=$1/platforms/$2/android.jar --disable-xquery --disable-jemacs || (echo "Failed to configure Kawa!"; exit 1)
 # Because kawa docs sometimes fail to build.
 echo '' > doc/kawa.texi
-make
+make || (echo "Failed to build Kawa!"; exit 1)
+cd ..
+rm kawa-1.13.tar.gz
+ln -s `pwd`/kawa/kawa-1.*.jar kawa/kawa.jar
+echo
+echo "Done! We're good to go"
